INSERT INTO Direccion (calle, numero, ciudad, pueblo, paraje) VALUES
('Av. 18 de Julio', '1234', 'Montevideo', '', ''),                       -- Montevideo (ciudad)
('Calle Lecueder', '101', 'Artigas', '', ''),                           -- Artigas (ciudad)
('Calle Batlle y Ordóñez', '202', 'Canelones', '', ''),                -- Canelones (ciudad)
('Ruta 26', 'km 45', '', '', 'Paraje Quebracho'),                      -- Cerro Largo (zona rural)
('Calle General Flores', '404', 'Colonia del Sacramento', '', ''),     -- Colonia (ciudad)
('Ruta 14', 'km 180', '', 'Carlos Reyles', ''),                        -- Durazno (pueblo)
('Calle Independencia', '606', 'Trinidad', '', ''),                    -- Flores (ciudad)
('Camino al Obelisco', '707', '', '', 'Paraje La Macana'),             -- Florida (zona rural)
('Calle Sarandí', '808', 'Minas', '', ''),                             -- Lavalleja (ciudad)
('Av. Roosevelt', '909', 'Maldonado', '', ''),                         -- Maldonado (ciudad)
('Calle República Argentina', '111', 'Paysandú', '', ''),              -- Paysandú (ciudad)
('Ruta 2', 'km 302', '', 'Algorta', ''),                               -- Río Negro (pueblo)
('Calle Joaquín Suárez', '333', 'Rivera', '', ''),                     -- Rivera (ciudad)
('Ruta 15', 'km 12', '', '', 'Paraje India Muerta'),                   -- Rocha (zona rural)
('Calle Uruguay', '555', 'Salto', '', ''),                             -- Salto (ciudad)
('Calle Asamblea', '666', 'San José de Mayo', '', ''),                -- San José (ciudad)
('Calle Oribe', '777', '', 'Cardona', ''),                             -- Soriano (pueblo)
('Ruta 5', 'km 256', '', '', 'Paraje El Molinillo'),                   -- Tacuarembó (zona rural)
('Calle Manuel Meléndez', '999', 'Treinta y Tres', '', '');            -- Treinta y Tres (ciudad)
