INSERT INTO Establecimiento (nombre, tipo, numeroDepartamento) VALUES
('Escuela 1 Montevideo', 'Centro Educativo', 1),
('Escuela 2 Artigas', 'Centro Educativo', 2),
('Escuela 3 Canelones', 'Centro Educativo', 3),
('Escuela 4 Cerro Largo', 'Centro Educativo', 4),
('Escuela 5 Colonia', 'Centro Educativo', 5),
('Escuela 6 Durazno', 'Centro Educativo', 6),
('Escuela 7 Flores', 'Centro Educativo', 7),
('Escuela 8 Florida', 'Centro Educativo', 8),
('Escuela 9 Lavalleja', 'Centro Educativo', 9),
('Escuela 10 Maldonado', 'Centro Educativo', 10),
('Escuela 11 Paysandú', 'Centro Educativo', 11),
('Escuela 12 Río Negro', 'Centro Educativo', 12),
('Escuela 13 Rivera', 'Centro Educativo', 13),
('Escuela 14 Rocha', 'Centro Educativo', 14),
('Escuela 15 Salto', 'Centro Educativo', 15),
('Escuela 16 San José', 'Centro Educativo', 16),
('Escuela 17 Soriano', 'Centro Educativo', 17),
('Escuela 18 Tacuarembó', 'Centro Educativo', 18),
('Escuela 19 Treinta y Tres', 'Centro Educativo', 19);
